### ISSUE TITLE
Hangs on Google Cloud Storage

### ISSUE THREAD

**Issue by blackjack75** [twitter/CocoaSPDY#46]
Why would the following code hang when the url points to google cloud storage (which supports SPDY) and not when using api.twitter.com for example?

```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [SPDYURLConnectionProtocol registerOrigin:@"https://storage.googleapis.com:443"];
        NSString* url = @"https://storage.googleapis.com:443/exoweatherimg.appspot.com/blue/tile_z4/x8_y6.jpg";
        NSURLRequest* request = [NSURLRequest requestWithURL: [NSURL URLWithString: url]];
        NSError* error =nil;
        NSURLResponse* resp;
        NSData* imageData = [NSURLConnection sendSynchronousRequest:request returningResponse:&resp error:&error];
        NSLog(@"SPDY received data:%i", [imageData length]);
    });

```

**Comment by kgoodier** [comment]
Well, this is a bit old, but to follow-up anyway with a guess, it's likely due to NPN. See the note in the readme, but basically Google's server is probably expecting to use NPN to negotiate SPDY, whereas CocoaSPDY is just going to start speaking SPDY right off the bat. If Google's server isn't built to parse the first few bytes and detect this, it will just see garbage.
